# Linear Progession

In [1]:
import numpy as np
import  matplotlib
%matplotlib inline 

#### Skeleton Code

In [2]:

# Object Neural Network
class Neural_Network : 

    # Melakukan inisiasi
    def __init__ (NN, innodes, hdnodes, outnodes, lr) :

        # Mensetting setiap nodes

        NN.input_nodes = innodes 
        NN.hidden_nodes = hdnodes
        NN.output_nodes = outnodes
        
        # Mensetting learning rate
        NN.learning_rate = lr

        pass

    # Melatih data    
    def train () :

        pass
    
    # Bertanya
    def query () :

        pass

    pass


In [3]:
# Memasukan nilai pada 3 nodes

input_node = 3
hidden_node = 3
output_node = 3

# Memasukan besar dari learning rate

learning_rate = 0.5

hasil = Neural_Network (input_node, hidden_node, output_node, learning_rate)


In [34]:
weight = np.random.rand (3, 3) - 0.5 # link weight secara random dari (-0.1 sampe +0.1) 
print (weight)

[[-0.37055153 -0.28320017 -0.05988614]
 [ 0.13040697 -0.22122674  0.13840516]
 [ 0.31175703 -0.17299173  0.14993451]]


#### Coba hal lain

In [51]:
x = np.random.randint (1, 3, size= (2,2))
# 1 = batas bawah, 3 = batas atas, size = bentuk
print (x)

print ("\n")

x = np.random.randn (3,3)
# randn = standard normal distribusi
print (x)

print ("\n")

s = np.random.normal (loc=0.1, scale=10.0, size=(2,2)) 
# loc = mean, scale = standard deviasi, size = bentuk 
print (s)

[[1 1]
 [1 2]]


[[ 0.7535378   0.57243135  1.50174484]
 [ 1.21957807  0.89716804 -1.69656359]
 [ 0.21830236  0.91924154  0.32473574]]


[[-13.78480046 -15.26619039]
 [  1.64860117  10.23151436]]
